groups:
- name: DemoAlerts
  rules:
  - alert: HighErrorRate
    expr: rate(http_request_duration_seconds_count{code="500"}[30s]) > 0.05
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: "High Error Rate on {{ $labels.job }}"
      description: "Error rate is too high, possible CPU overload or incident."

  - alert: HighLatency
    expr: rate(http_request_duration_seconds_sum[30s]) / rate(http_request_duration_seconds_count[30s]) > 0.5
    for: 15s
    labels:
      severity: warning
    annotations:
      summary: "High Latency on {{ $labels.job }}"
      description: "Latency is above 500ms."

  - alert: ServiceDown
    expr: up == 0
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: "Service Down: {{ $labels.job }}"
      description: "The service is unreachable."
