global:
  scrape_interval: 5s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:4000']
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:4001']
  - job_name: 'worker-service'
    static_configs:
      - targets: ['worker-service:4002']
